name: Build and deploy report
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v3
      - name: Clean install
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify
      - name: Run Rescue tests
        run: npm run rescue
        continue-on-error: true
      - name: Combine reports
        run: npm run rescue
        continue-on-error: true
      - name: Deploy report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/mochareports
      - name: Slack notification with cypress-slack-reporter
        if: always()
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
        run: |
          npx cypress-slack-reporter --report-dir cypress/reports/mochareports --ci-provider none
